#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# run script for multiple monitors
if [ -x /bin/bspwm_connect_monitors.sh ];then 
	# connect multiple monitors
	bspwm_connect_monitors.sh

	# define desktops for multiple monitors
	bspc monitor eDP1 -d I II III IV V 
	bspc monitor HDMI2 -d VI VII VIII IX X
	bspc monitor eDP1 -s HDMI2
else
	# define desktops for single monitor
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer   true

bspc rule -a Zathura state=tiled

# set padding on all sides
for side in top right bottom left; do bspc config ${side}_monocle_padding 100; done

# Start Other Essential Programs
nitrogen --restore & 				# wallpaper service
~/.config/polybar/launch.sh &			# start polybar
picom --config ~/.config/picom/picom.conf & 	# start compositor
